



export const SUCCESS_GEN_RAND_NUM = 'SUCCESS_GEN_RAND_NUM'
export const FAIL_GEN_RAND_NUM = 'FAIL_GEN_RAND_NUM'

export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'

export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'







export const FETCH_SESSION = 'FETCH_SESSION'